version: "3.9"

networks:
  proxy:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    container_name: goat_routing
    hostname: goat_routing
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "6000:6000"
      - "8000:8000"
    networks:
      proxy:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      proxy:

  redis:
    image: redis:latest
    networks:
      proxy:

  celery-worker:
    build: .
    command: celery -A src.core.worker worker -c 1 --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
    networks:
      proxy:
